[package]
name = "adb-transport"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Implementation of ADB transport (USB) protocol"

[dependencies]
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.41"
nusb = "0.1.12"
derive_more = { version = "2.0.1", features = ["error", "debug", "display", "try_from", "from"] }
bytes = "1.10.0"
enum_dispatch = "0.3.13"
bstr = "1.11.3"
parking_lot = "0.12.3"
rsa = "0.9.7"
num-traits = "0.2.19"
num-bigint-dig = "0.8.4"
base64 = "0.22.1"
sha1 = { version = "0.10.6", features = ["oid"] }
flume = "0.11.1"
dashmap = "6.1.0"
diatomic-waker = "0.2.3"
